### ISSUE TITLE
Can't install `babel-preset-react-app`.

### ISSUE THREAD

**Issue by darkyen** [auth0-community/auth0-react-scripts#5]
As reported on the public forum https://auth0.com/forum/t/auth0-react-scripts-fails/5067 the react-script fails to install `babel-preset-react-app`.

**Comment by cwoodruff** [comment]
Is there any update when this will be resolved?

**Comment by jschilperoord** [comment]
Also running in to this problem. Is there any update regarding a fix for this issue ?

**Comment by dcanning** [comment]
this is the same as [issue 4](https://github.com/auth0-community/auth0-react-scripts/issues/4)

**Comment by beardaway** [comment]
Hey there everyone !

Terribly sorry for such delay in response! At the time the tool hosted in the repo was developed we didn't have enough bandwidth to implement it further that's why we kinda decided to "outsource" it to our community developers.

For now we are gradually expanding the team and we're aiming that at some point in the future we'll be able to maintain and develop this repo more effectively. Sorry for any inconvenience!
